server:
  port: 20010
  servlet:
    context-path: /base-component
spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
  application:
    name: base-component
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.98:18848
        group: shadowlayover
        namespace: local
        ip: 192.168.1.98
      config:
        server-addr: 192.168.1.98:18848
        group: shadowlayover
        name: base-component
        namespace: local
  datasource:
    url: jdbc:mysql://192.168.1.98:13306/shadowlayover_component
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
shadowlayover:
  seata:
    application-id: component_seata-server
    tx-service-group: my_test_tx_group
    namespace: seata
    username: nacos
    password: nacos
  mybatis-plus:
    multi-tenant:
      ignore-tables:
        - sys_config
  log:
    path: /Users/zhouzq/shadowlayover/logs/
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
