server:
  port: 30000
spring:
  profiles:
    active: dev
  application:
    name: base-platform-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.98:18848
        group: shadowlayover
        namespace: 54c84fc9-f0b8-44e1-8c89-e5b932161771
        ip: 192.168.1.98
      config:
        server-addr: 192.168.1.98:18848
        group: shadowlayover
        name: base-platform-gateway
        namespace: 54c84fc9-f0b8-44e1-8c89-e5b932161771
    gateway:
      routes:
        - id: base-oauth
          uri: lb://base-oauth
          predicates:
            - Path=/base-oauth/**
        - id: base-message
          uri: lb://base-message
          predicates:
            - Path=/base-message/**
  redis:
    host: 192.168.1.98
    port: 16379
  cache:
    multi:
      cache-names:
        - base-platform
      cachePrefix: platform
shadowlayover:
  log:
    path: D:\shadowlayover-workplace\logs\