server:
  port: 30000
  servlet:
    context-path: /base-platform
spring:
  profiles:
    active: dev
  application:
    name: base-platform-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.98:18848
        group: shadowlayover
        namespace: 54c84fc9-f0b8-44e1-8c89-e5b932161771
        ip: 192.168.1.98
      config:
        server-addr: 192.168.1.98:18848
        group: shadowlayover
        name: base-platform-gateway
        namespace: 54c84fc9-f0b8-44e1-8c89-e5b932161771
shadowlayover:
  log:
    path: D:\shadowlayover-workplace\logs\