server:
  port: 30000
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: base-platform-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.98:18848
        group: shadowlayover
        namespace: local
        ip: 192.168.1.98
      config:
        server-addr: 192.168.1.98:18848
        group: shadowlayover
        name: base-platform-gateway
        namespace: local
      routes:
        - id: base-oauth
          uri: lb://base-oauth
          predicates:
            - Path=/base-oauth/**
        - id: base-message
          uri: lb://base-message
          predicates:
            - Path=/base-message/**
  redis:
    host: 192.168.1.98
    port: 16379
shadowlayover:
  gateway:
    ignore-urls:
      - /base-oauth/oauth/token
  log:
    path: D:\shadowlayover-workplace\logs\