server:
  port: 20000
  servlet:
    context-path: /base-oauth
spring:
  profiles:
    active: dev
  application:
    name: base-oauth
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.98:18848
        group: shadowlayover
        namespace: 7c27bc92-779f-4112-a13a-45509795119a
        ip: 192.168.1.98
      config:
        server-addr: 192.168.1.98:18848
        group: shadowlayover
        name: base-oauth
        namespace: 7c27bc92-779f-4112-a13a-45509795119a
  redis:
    host: 192.168.1.98
    port: 16379
  cache:
    multi:
      cache-names:
        - base-oauth
      cachePrefix: oauth
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url: jdbc:mysql://192.168.1.98:13306/shadowlayover_oauth
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
shadowlayover:
  log:
    path: /Users/zhouzq/shadowlayover/logs/