server:
  port: 10000
  servlet:
    context-path: /base-oauth
spring:
  application:
    name: base-oauth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:18848
        group: shadowlayover
        namespace: e037d3cb-53b7-4175-b95c-ee6467983bd8
      config:
        server-addr: 127.0.0.1:18848
        group: shadowlayover
        name: base-oauth
        namespace: e037d3cb-53b7-4175-b95c-ee6467983bd8

  security:
    oauth2:
      client:
        registration:
          shadowlayover:
            redirect-uri:
  profiles:
    active: dev
shadowlayover:
  log:
    path: /Users/zhouzq/shadowlayover/logs/
