server:
  port: 20010
  servlet:
    context-path: /base-component
spring:
  profiles:
    active: dev
  application:
    name: base-component
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.98:18848
        group: shadowlayover
        namespace: 54c84fc9-f0b8-44e1-8c89-e5b932161771
        ip: 192.168.1.98
      config:
        server-addr: 192.168.1.98:18848
        group: shadowlayover
        name: base-component
        namespace: 54c84fc9-f0b8-44e1-8c89-e5b932161771
  datasource:
    dynamic:
      primary: master
      strict: true
      seata: true
      seata-mode: at
      datasource:
        master:
          url: jdbc:p6spy:mysql://192.168.1.98:13306/shadowlayover_component
          username: root
          password: 123456
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
mybatis-plus:
  mapper-locations: classpath*:/mappers/*.xml
shadowlayover:
  seata:
    application-id: base-component-seata
    tx-service-group: my_test_tx_group
    namespace: 8bd73b4e-2b8f-4ffe-bd19-a64b1837d02a
    username: nacos
    password: nacos
  mybatis-plus:
    multi-tenant:
      ignore-tables:
        - sys_config
  log:
    path: /Users/zhouzq/shadowlayover/logs/