server:
  port: 20010
  servlet:
    context-path: /base-component
spring:
  profiles:
    active: dev
  application:
    name: base-component
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.98:18848
        group: shadowlayover
        namespace: 54c84fc9-f0b8-44e1-8c89-e5b932161771
        ip: 192.168.1.98
      config:
        server-addr: 192.168.1.98:18848
        group: shadowlayover
        name: base-component
        namespace: 54c84fc9-f0b8-44e1-8c89-e5b932161771
  datasource:
    dynamic:
      primary: master
      strict: true
      seata: true
      seata-mode: at
      datasource:
        master:
          url: jdbc:mysql://192.168.1.98:13306/shadowlayover_component
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
seata:
  enabled: true
  enable-auto-data-source-proxy: false
  application-id: seata-server
  tx-service-group: my_test_tx_group
  service:
    vgroup-mapping:
      my_test_tx_group: default
    grouplist:
      default: 192.168.1.98:18091
  config:
    type: nacos
    nacos:
      server-addr: ${spring.cloud.nacos.config.server-addr}
      group: SEATA_GROUP
      namespace: '8bd73b4e-2b8f-4ffe-bd19-a64b1837d02a'
      username: nacos
      password: nacos
      data-id: seata.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: ${spring.cloud.nacos.discovery.server-addr}
      group: 'SEATA_GROUP'
      namespace: '8bd73b4e-2b8f-4ffe-bd19-a64b1837d02a'
      username: nacos
      password: nacos
shadowlayover:
  log:
    path: /Users/zhouzq/shadowlayover/logs/